swiftmailer:
    default_mailer: mailer_2565
    mailers:
        mailer_2565:
            transport: gmail
            username: arilystagent@gmail.com
            password: Y3B1ZiB4ZWVjIGlybHkganR6dA==
            # sender_address: ~
            # delivery_addresses: ~
            disable_delivery: false

